# Generated by Django 3.0.7 on 2022-04-23 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=50)),
                ('year', models.IntegerField(default=0)),
                ('selling_price', models.IntegerField(default=0)),
                ('present_price', models.IntegerField(default=0)),
                ('kms_driven', models.IntegerField(default=0)),
                ('pub_date', models.DateField()),
                ('owner', models.CharField(max_length=100)),
                ('fuel_type', models.CharField(max_length=50)),
                ('image', models.ImageField(default='', upload_to='car/images')),
            ],
        ),
    ]
