# Generated by Django 3.0.7 on 2022-05-01 12:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='pub_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
