# Generated by Django 3.0.7 on 2022-05-01 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cars', '0002_auto_20220501_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='car_type',
            field=models.CharField(default='SEDAN', max_length=50),
        ),
    ]
