# Generated by Django 3.0.7 on 2022-06-17 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cars', '0004_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='phone',
            field=models.IntegerField(default=0),
        ),
    ]
